# 「近すぎる」の閾値
# 同じ単語が以下の文字数未満の間隔で繰り返されたときに警告マークを付けます。
distance_threshold = 100

# 固有名詞のリスト
# 分割されてほしくない単語が分割されてしまうときはこのリストに追加してください。
proper_nouns = [
    "巨大娘",
    "夢愛",
]

# 無視する品詞
# 単語の品詞は出力されたHTMLで単語をポイントすると表示されます。
ignores = [
    "空白",
    "記号",
    "補助記号",
    "助詞",
    "助動詞",
]
